### ISSUE TITLE
Add TWA to Android PWA Wrapper

### ISSUE THREAD

**Issue by MrSaikatS** [xtools-at/Android-PWA-Wrapper#13]
Hi, i'm tring to add TWA (Trusted Web Activities). i followed the guide on https://developers.google.com/web/updates/2019/02/using-twa it give a lot of error. can anyone help me with this? Thanks in advanced.

**Comment by xtools-at** [comment]
I've skimmed the docs, it seems that TWAs are more or less a substitute for this project - you create a simple Android app that launches your PWA via the browser in fullscreen.
So I guess the 2 approaches are exclusive, you either create a TWA or use the PWA-Wrapper. What exactly are you trying to achieve?

**Comment by MrSaikatS** [comment]
i wanted to to add "**TWA**" to your **PWA-Wrapper**. is it possible to do?

**Comment by xtools-at** [comment]
I may be wrong, but I don't see how it would make sense, after understanding what TWAs are (= a standalone thing doing something similar like this wrapper). 

Metaphorically speaking, you're asking to integrate a Beamer into a TV, which doesn't make sense since both are means to the same end (though they work differently) and are substituting each other. Ofc, you can have both a TV and a Beamer, but you can't put one into the other. 

But feel free to try yourself.

**Comment by MrSaikatS** [comment]
oh, that means "**PWA-Wrapper**" already comes with the features which "**TWA**" is providing.
